In [2]:
import tensorflow as tf

In [11]:
# 定義𝑧=𝑤2cos(𝑥)+𝑏，𝐿=𝑧−𝑦2，其中，𝑤與𝑏是Tensor變數(tf.Variable)，𝑥與𝑦是Tensor常數。
# 假設𝑤=1,𝑏=−0.5,𝑥=0.5,𝑦=1。
# 請使用tf.GradientTape建立一個梯度物件來求得變數𝑤與常數𝑥的梯度值：Τ𝜕𝐿𝜕𝑤,Τ𝜕𝐿𝜕𝑥
# 提示：tf.GradientTape計算常數𝑥的梯度，需要使用梯度物件的.watch函數對它進行額外的處理。
# 要使用一個梯度物件來要求得一個以上的梯度值，需要在建立梯度物件設定persistent屬性。

w = tf.Variable(1.0); b = tf.Variable(-0.5);
x = tf.convert_to_tensor([0.5]); y = tf.convert_to_tensor([1.0])

with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    z = tf.add(tf.multiply(tf.pow(w, 2), tf.cos(x)) ,b) 
    L =tf.pow(z - y, 2)
    print("z = ", z)
    print("L = ", L)
print("dL/dw = ", tape.gradient(L, w))
print("dL/dx = ", tape.gradient(L, x))
    

z =  tf.Tensor([0.37758255], shape=(1,), dtype=float32)
L =  tf.Tensor([0.38740346], shape=(1,), dtype=float32)
dL/dw =  tf.Tensor(-2.1848905, shape=(), dtype=float32)
dL/dx =  tf.Tensor([0.5968056], shape=(1,), dtype=float32)
